### PR TITLE
Scope discovery-ec2 IMDS lookups to this cluster formation.

### LINKED ISSUE #34: [BUG] Cluster formation probes manager nodes from other clusters
### What is the bug?

When starting multiple clusters with different names, the second cluster will attempt to connect to nodes belonging to the first cluster.

### How can one reproduce the bug?

Start a 2.8.0 cluster.

```
cdk deploy "*"  -c distributionUrl=https://artifacts.opensearch.org/releases/bundle/opensearch/2.8.0/opensearch-2.8.0-linux-x64.tar.gz -c region=us-east-1 -c suffix=280-multinode -c securityDisabled=true -c cpuArch=x64 -c singleNodeCluster=false -c distVersion=2.8.0 -c minDistribution=false -c serverAccessType=prefixList -c restrictServerAccessTo=pl-60b85b09 -c dataNodeCount=3 -c use50PercentHeap=true -c isInternal=false
```

The logs will contain attempts to discover "manager" nodes from IMDS. Note that 3 nodes are probed.

```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                     message                                                                                                      |
|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1686232341359 | [2023-06-08T13:52:21,147][DEBUG][o.o.d.e.Ec2ClientSettings] [ip-10-0-4-253.ec2.internal] Using either environment variables, system properties or instance profile credentials                                   |
| 1686232345883 | [2023-06-08T13:52:24,499][DEBUG][o.o.d.e.Ec2DiscoveryPlugin] [ip-10-0-4-253.ec2.internal] Register _ec2_, _ec2:xxx_ network names                                                                                |
| 1686232347135 | [2023-06-08T13:52:27,117][DEBUG][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-4-253.ec2.internal] using host_type [private_ip], tags [{role=[manager]}], groups [[]] with any_group [true], availability_zones [[]] |
| 1686232349391 | [2023-06-08T13:52:28,357][DEBUG][o.o.d.e.AwsEc2ServiceImpl] [ip-10-0-4-253.ec2.internal] Using default provider chain                                                                                            |
| 1686232349392 | [2023-06-08T13:52:29,141][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-4-253.ec2.internal] finding seed nodes...                                                                                             |
| 1686232349392 | [2023-06-08T13:52:29,141][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-4-253.ec2.internal] adding i-0ddd0e351118ac2f0, address 10.0.4.169, transport_address 10.0.4.169:9300                                 |
| 1686232349392 | [2023-06-08T13:52:29,142][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-4-253.ec2.internal] adding i-08a85ecbd5a3476b1, address 10.0.5.160, transport_address 10.0.5.160:9300                                 |
| 1686232349392 | [2023-06-08T13:52:29,142][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-4-253.ec2.internal] adding i-0cece6c687d562ee4, address 10.0.5.176, transport_address 10.0.5.176:9300                                 |
| 1686232349392 | [2023-06-08T13:52:29,142][DEBUG][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-4-253.ec2.internal] using dynamic transport addresses [10.0.4.169:9300, 10.0.5.160:9300, 10.0.5.176:9300]                             |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Start a 2.7.0 cluster.

```
cdk deploy "*"  -c distributionUrl=https://artifacts.opensearch.org/releases/bundle/opensearch/2.7.0/opensearch-2.7.0-linux-x64.tar.gz -c region=us-east-1 -c suffix=270-multinode -c securityDisabled=true -c cpuArch=x64 -c singleNodeCluster=false -c distVersion=2.7.0 -c minDistribution=false -c serverAccessType=prefixList -c restrictServerAccessTo=pl-60b85b09 -c dataNodeCount=3 -c use50PercentHeap=true -c isInternal=false
```

The logs will contain attempts to discover manager nodes from IMDS. Note that 6 nodes are probed.

```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                               message                                                                                                               |
|---------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1686235093131 | [2023-06-08T14:38:13,095][DEBUG][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-76.ec2.internal] using host_type [private_ip], tags [{role=[manager]}], groups [[]] with any_group [true], availability_zones [[]]                     |
| 1686235095386 | [2023-06-08T14:38:15,172][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-76.ec2.internal] finding seed nodes...                                                                                                                 |
| 1686235095386 | [2023-06-08T14:38:15,173][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-76.ec2.internal] adding i-07b07c9b15d4c957f, address 10.0.4.54, transport_address 10.0.4.54:9300                                                       |
| 1686235095386 | [2023-06-08T14:38:15,174][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-76.ec2.internal] adding i-0ddd0e351118ac2f0, address 10.0.4.169, transport_address 10.0.4.169:9300                                                     |
| 1686235095386 | [2023-06-08T14:38:15,174][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-76.ec2.internal] adding i-07f7610d0e749baf6, address 10.0.5.79, transport_address 10.0.5.79:9300                                                       |
| 1686235095386 | [2023-06-08T14:38:15,175][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-76.ec2.internal] adding i-08a85ecbd5a3476b1, address 10.0.5.160, transport_address 10.0.5.160:9300                                                     |
| 1686235095386 | [2023-06-08T14:38:15,175][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-76.ec2.internal] adding i-0cece6c687d562ee4, address 10.0.5.176, transport_address 10.0.5.176:9300                                                     |
| 1686235095386 | [2023-06-08T14:38:15,175][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-76.ec2.internal] adding i-0fac0727ff8f1ea7d, address 10.0.3.81, transport_address 10.0.3.81:9300                                                       |
| 1686235095386 | [2023-06-08T14:38:15,176][DEBUG][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-76.ec2.internal] using dynamic transport addresses [10.0.4.54:9300, 10.0.4.169:9300, 10.0.5.79:9300, 10.0.5.160:9300, 10.0.5.176:9300, 10.0.3.81:9300] |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

This is because discovery-ec2 is looking for nodes tagged "manager" in the same region.

Suggest renaming "manager" to include the formation suffix.

### What is the expected behavior?

Only probe nodes from the current formation.

### What is your host/environment?

Linux

### Do you have any additional context?

This is harmless in that the nodes from the first cluster reject requests. However this is wasteful, and can cause confusion when running other versions in the same region. For example, in https://github.com/opensearch-project/OpenSearch/issues/7959 the user was getting version incompatibility errors because a newer cluster was being deployed in a region that had an older cluster.

```
java.lang.IllegalStateException: Received message from unsupported version: [2.8.0] minimal compatible version is: [2.9.0]
```

### PR DESCRIPTION
**Pull request by dblock**
### Description

Scope discovery-ec2 IMDS lookups for seed/manager nodes down to this cluster. Here's a successful output.

```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                                                                    message                                                                                                                                                     |
|---------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1686244606265 | [2023-06-08T17:16:46,146][DEBUG][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-156.ec2.internal] using host_type [private_ip], tags [{Name=[opensearch-infra-stack-270-multinode/seedNodeAsg, opensearch-infra-stack-270-multinode/managerNodeAsg]}], groups [[]] with any_group [true], availability_zones [[]] |
| 1686244608270 | [2023-06-08T17:16:48,118][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-156.ec2.internal] finding seed nodes...                                                                                                                                                                                           |
| 1686244608270 | [2023-06-08T17:16:48,119][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-156.ec2.internal] adding i-0e1b8f3a73ed4195b, address 10.0.4.146, transport_address 10.0.4.146:9300                                                                                                                               |
| 1686244608270 | [2023-06-08T17:16:48,119][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-156.ec2.internal] adding i-0bad8a1561668117f, address 10.0.5.216, transport_address 10.0.5.216:9300                                                                                                                               |
| 1686244608270 | [2023-06-08T17:16:48,120][TRACE][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-156.ec2.internal] adding i-0a452e2dfdc05691f, address 10.0.3.33, transport_address 10.0.3.33:9300                                                                                                                                 |
| 1686244608520 | [2023-06-08T17:16:48,120][DEBUG][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-156.ec2.internal] using dynamic transport addresses [10.0.4.146:9300, 10.0.5.216:9300, 10.0.3.33:9300]                                                                                                                            |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

I tried using `aws:cloudformation:stack-name`, but OpenSearch doesn't support settings named `discovery.ec2.tag.aws:cloudformation:stack-name`.

### Issues Resolved

Fixes #34.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: lib/infra/infra-stack.ts [hunk 1]
```diff
@@ -425,6 +425,10 @@ export class InfraStack extends Stack {
       const baseConfig: any = load(readFileSync(`${configFileDir}/multi-node-base-config.yml`, 'utf-8'));
 
       baseConfig['cluster.name'] = `${scope.stackName}-${scope.account}-${scope.region}`;
+
+      // use discovery-ec2 to find manager nodes by querying IMDS
+      baseConfig['discovery.ec2.tag.Name'] = `${scope.stackName}/seedNodeAsg,${scope.stackName}/managerNodeAsg`;
```
Comment (rishabh6788) [inline lib/infra/infra-stack.ts:430]: The same tag name should be associated with ec2 nodes as well, right?
https://github.com/opensearch-project/opensearch-cluster-cdk/blob/main/lib/infra/infra-stack.ts#L195

Comment (dblock) [reply lib/infra/infra-stack.ts:430]: It's already there. Here's what a node gets:

Screenshot 2023-06-08 at 1 58 09 PM

**Review by rishabh6788 — APPROVED** [review]
